server:
  port: 9090

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:9091/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:9091/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true